### ISSUE TITLE
better way to do dependency injection?

### ISSUE THREAD

**Issue by beenotung** [mistlog/svelte-draft-todo-mvc#1]
The current 'render' function seems taking all dependencies from the context in 'angular 1 style', that is from the function argument. This approach may not scale when the number of arguments growth?
The example in the repo is a function with quite a lot number of arguments.

https://github.com/mistlog/svelte-draft-todo-mvc/blob/0a9d15309caca7f81a0a6184c931b09396e157b0/src/App.tsx#L157

**Comment by mistlog** [comment]
> The current 'render' function seems taking all dependencies from the context in 'angular 1 style', that is from the function argument. This approach may not scale when the number of arguments growth?
> The example in the repo is a function with quite a lot number of arguments.
> 
> https://github.com/mistlog/svelte-draft-todo-mvc/blob/0a9d15309caca7f81a0a6184c931b09396e157b0/src/App.tsx#L157

Yes, currently I figured out 3 possible ways to improve this.

1. write code just like what we do in svelte, i.e. write everthing in the "render" function, or the ```export default App(...)```. For example: https://github.com/mistlog/svelte-draft-template/blob/master/src/App.tsx#L10. I rewrite App.tsx in this way, see https://gist.github.com/mistlog/a1d172b22f94a007e54e69a5ce25adc4

We can see from this example that it's totally ok to write program in the traditional way.

As we don't want to write everything in a single place and want to reorder code(the goal of literate programming, see https://github.com/microsoft/TypeScript/issues/31364#issuecomment-568246725), we want to improve the language itself. Currently, we have to write all deps in argument in a [local context](https://github.com/mistlog/typedraft-docs/blob/master/concepts/concepts.md#local-context), that's the limitation of the language: 

2. improve the typedraft language: the arguments are here only for type check, see https://github.com/mistlog/typedraft-docs/blob/master/concepts/concepts.md#local-context. So it's ok to write nothing in the param list but the IDE will hint "can find ...", thus we can implement a specific language server for typedraft.

3. improve the way we write jsx: when we write something like this, we have to write the jsx as a whole. We can implement something like "inline component",which works in the same way with local context, for example:

instead of write:

```typescript
export function UI(a:number, b:number){
     <div>
         <div>{a}</div>
         <div>{b}</div>
     </div>
}
```

we can write it in this way, group related UI and state all together and use props on demand.
```typescript
export function UI(){
    <div>
          <InlineComponentA/>
          <InlineComponentB/>
    </div>
}  

function InlineComponentA(a: number){
   <div>{a}</div>
}

function InlineComponentB(b: number){
   <div>{b}</div>
}
```

**Comment by beenotung** [comment]
The rewrite in option 1 seems better;
the option 3 makes the props implicit, some bad magic may happens when we accidentally introduce name collision.

**Comment by mistlog** [comment]
Yes, although name collision can be detected in compile time, but it's not convenient to "watch" the error message. If we can integrate it into code intelligence in IDE, then option 3 makes sense. As typedraft is a superset of typescript, so the new way to write code is optional and we can insist on option 1.
